language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - egracianihiguero@gmail.com
script:
#Test unitario y de integracion en develop
- mvn clean verify --settings settings.xml
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=egraciani-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3911eaff3c62d11185eebff585e7e105ae5489fe --settings settings.xml